apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false

  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686
    editable: false

  - name: QuestDB
    type: postgres
    access: proxy
    url: questdb:8812
    database: qdb
    user: admin
    secureJsonData:
      password: quest
    editable: false
    jsonData:
      sslmode: disable
      maxOpenConns: 5
      maxIdleConns: 2
      connMaxLifetime: 14400

  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: naia
    user: naia
    secureJsonData:
      password: naia_dev_password
    editable: false
    jsonData:
      sslmode: disable
      maxOpenConns: 5
      maxIdleConns: 2
